# Generated by Django 5.0.6 on 2024-06-24 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128, unique=True, verbose_name='Зав. № машины')),
                ('model_technique', models.CharField(max_length=128, verbose_name='Модель техники')),
                ('model_engine', models.CharField(max_length=128, verbose_name='Модель двигателя')),
                ('serial_engine', models.CharField(max_length=128, verbose_name='Зав. № двигателя')),
                ('model_transmission', models.CharField(max_length=128, verbose_name='Модель трансмиссии')),
                ('serial_transmission', models.CharField(max_length=128, verbose_name='Зав. № трансмиссии')),
                ('model_drive_axle', models.CharField(max_length=128, verbose_name='Модель ведущего моста')),
                ('serial_drive_axle', models.CharField(max_length=128, verbose_name='Зав. № ведущего моста')),
                ('model_steering_axle', models.CharField(max_length=128, verbose_name='Модель управляемого моста')),
                ('serial_steering_axle', models.CharField(max_length=128, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract', models.CharField(max_length=128, verbose_name='Договор поставки')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=128, verbose_name='Адрес поставки (эксплуатации)')),
                ('configuration', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_machines', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=128, verbose_name='Вид ТО')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=128, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Зав. № машины')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО')),
            ],
            options={
                'verbose_name': 'Обслуживание',
                'verbose_name_plural': 'Обслуживания',
                'ordering': ['maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('failure_unit', models.CharField(max_length=128, verbose_name='Узел отказа')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('recovery_method', models.CharField(max_length=128, verbose_name='Способ восстановления')),
                ('used_spare_parts', models.TextField(verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(verbose_name='Время простоя техники')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine', verbose_name='Зав. № машины')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['failure_date'],
            },
        ),
    ]
