# Generated by Django 5.0.6 on 2024-06-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('model_technique', models.CharField(max_length=255)),
                ('model_engine', models.CharField(max_length=255)),
                ('serial_engine', models.CharField(max_length=255)),
                ('model_transmission', models.CharField(max_length=255)),
                ('serial_transmission', models.CharField(max_length=255)),
                ('model_drive_axle', models.CharField(max_length=255)),
                ('serial_drive_axle', models.CharField(max_length=255)),
                ('model_steering_axle', models.CharField(max_length=255)),
                ('serial_steering_axle', models.CharField(max_length=255)),
                ('delivery_contract', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_machines', to=settings.AUTH_USER_MODEL)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=255)),
                ('maintenance_date', models.DateField()),
                ('operating_time', models.PositiveIntegerField()),
                ('order_number', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_time', models.PositiveIntegerField()),
                ('failure_unit', models.CharField(max_length=255)),
                ('failure_description', models.TextField()),
                ('recovery_method', models.CharField(max_length=255)),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.PositiveIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
